plugin.multiplechoice=co.unicauca.bancopreguntas.plugins.MultipleChoiceQuestionPlugin
plugin.case=co.unicauca.bancopreguntas.plugins.CaseQuestionPlugin
plugin.pipeline=co.unicauca.bancopreguntas.plugins.PipelineQuestionPlugin
